### ISSUE TITLE
Persisting and synchronizing data.

### ISSUE THREAD

**Issue by ArnoBuschmann** [arqex/freezer#11]
Hey Javi,

Today I stumbled over LokiJS, a leightweight JS database, that can run on a server and the browsers local storage. I think, this can have nice advantages over using just a server-side db, say Mongo for example.

I made up some questions here, maybe you want to check? Would be interested on your thoughts :)

https://github.com/techfort/LokiJS/issues/109

Cheers, Arno

**Comment by arqex** [comment]
Hi @ArnoBuschmann 

Sorry for my delay replying, a lot of work, I will try to have a look at it later :)

**Comment by ArnoBuschmann** [comment]
Hi Javi, no problem at all, hope you are all well! :) As we discussed about isomorphism I just thought you might find databases in the browser interesting too. The browsers IndexedDB is capable of storing up to 50 mb (or even more with permission). Combined with an ability to synchronize stable with a server, this adds a completely new point of view on how isomorphism could be handled.
