### ISSUE TITLE
Improve transaction support for data changes

### ISSUE THREAD

**Issue by zerkalica** [arqex/freezer#2]
Is analog Immutable.withMutations for atomic data changes?

In this example only first array change will trigger update listener:

```js
var state = new Freezer({arr: [0,1,2,3,4], a: {b: {bb: 1, cc: 2}, c: {cc: 2}}})
var data = state.get();

data.arr.getListener().on('update', (data) => {
    console.log(data)
})

data.arr
    .push( 5 ) // [0,1,2,3,4,5]
    .pop() // [0,1,2,3,4]
    .unshift( 'a' ) // ['a',0,1,2,3,4]
    .shift() // [0,1,2,3,4]
    .splice( 1, 1, 'a', 'b') // [ 0, 'a', 'b', 2, 3, 4]

// outputs { '0': 0, '1': 1, '2': 2, '3': 3, '4': 4, '5': 5 }
```

**Comment by arqex** [comment]
hi @zerkalica 

Thanks for ping me with the problem. It should trigger update just once, but the result should be as you said:


```js
[ 0, 'a', 'b', 2, 3, 4]
```
I will have a look at it tomorrow.

It doesn't work like immutable's `withMutations`, every operation will update the tree completely, creating a new frozen object, but all the operations in the same tick should trigger update just once with the final result of all of them. That way the components are only refreshed once.

Anyways, it should be great to have a way of applying multiple changes at once, like a database transaction isn't it? Something like;

```js
data.arr.transaction()
    .push( 5 ) // [0,1,2,3,4,5]
    .pop() // [0,1,2,3,4]
    .unshift( 'a' ) // ['a',0,1,2,3,4]
    .shift() // [0,1,2,3,4]
    .splice( 1, 1, 'a', 'b') // [ 0, 'a', 'b', 2, 3, 4]
    .run()
;
```
What do you think?

**Comment by zerkalica** [comment]
Looks good, but will it work with hashes, not only array?

```js
var store = new Freezer({
root: {
    a: {aa: {c: 1}},
    b: {bb: {cc: 321}},
    arr: [1, 2, 3, 4]
}
});

store.get().root.transaction()
.a.set({aa: {c: 123}}
.b.set({bb: {cc: 321}}
.arr.push(5)
.run()
```

**Comment by arqex** [comment]
We can work on it. Any ideas on how to?

**Comment by arqex** [comment]
@zerkalica 

I have released a new version fixing the parameter of the 'update' event. Transaction support will come in a future release.

Cheers,
Javi

**Comment by arqex** [comment]
@zerkalica 

Transactions are now working in freezer 0.5

https://github.com/arqex/freezer#batch-updates

I hope you like them.
