### ISSUE TITLE
Extending Freezer

### ISSUE THREAD

**Issue by kuraga** [arqex/freezer#22]
Good day, @arqex ! Thank you for your work!

I want to inherit `Freezer` in my class (in ECMAScript 6). What do you think about possibility of it?

But `Freezer.prototype` doesn't have any methods such as `get` and `set`. Can this be changed?

**Comment by arqex** [comment]
Hi @kuraga 

I can think of it for the next release. The reason because freezer does not have those methods in the prototype is because it stores the current frozen data using a closure to keep it private.

Maybe we can add it to the Freezer instance as an attribute like `_frozen` so it is possible to move those methods to the prototype.

Do you want to create a PR for that?

Cheers,
Javi

**Comment by kuraga** [comment]
Yes, I really want. But I'm not sure about my JavaScript competence. But I'll try :smile:

**Comment by kuraga** [comment]
@arqex , help me, please! What do you exactly propose? Thanks!

**Comment by kuraga** [comment]
Is `_frozen` you mentioned the same as [`frozen'](https://github.com/arqex/freezer/blob/711648507ca6a44bad14d85961c2f6f017a1d1c7/src/freezer.js#L14)?

**Comment by kuraga** [comment]
@arqex like that? kuraga/freezer@76b00396beb6ed14b57b7fa76e40636ee0ba2083
All tests are green.

**Comment by arqex** [comment]
Hi @kuranga

Thanks for your collaboration. I am out of my city without my laptop. I will have a look at your changes on wednesday.

Cheers

**Comment by kuraga** [comment]
Thanks! All actual info will be in comment above.

**Comment by rgrwkmn** [comment]
I tried out @kuraga's changes and now I can use babel. I was using jstransform before and had tried moving to babel due to an unrelated bug in jstransform.

**Comment by kuraga** [comment]
@rgrwkmn set `nonStandard` babel's option to `false`. First use JSX transformer, then Babel.

**Comment by kuraga** [comment]
@rgrwkmn Ah, sorry, you WANT move.....

**Comment by arqex** [comment]
Hi, sorry for the delay replying, but I was on holidays and my gf don't let me code! :smile:

I will review those changes, commiting them if they are ok right now.

**Comment by kuraga** [comment]
Ok, will done later

**Comment by kuraga** [comment]
See #25

**Comment by kuraga** [comment]
See #26
