### ISSUE TITLE
Best way to set multiple fields

### ISSUE THREAD

**Issue by aptheod** [arqex/freezer#35]
Suppose i have two classes. On the first i set the frozen data...

```js
var dataStore = new Freezer({
data: { 
array_1: [],
int_value: 0,
array_2: [],
bool_value: false
}
});
```

..and pass the `dataStore.get().data` as parameter on the constructor of the second one, on variable `this.data`. Now i want to assign some values to these fields. What's the best way to do it?

```js
this.data = this.data.set({int_value: 5});
this.data = this.data.set({array_2: [1,2 ,3]});
this.data = this.data.array_1.append( [4, ,5 ,6] ); 
```
This way is working, since i don't have get() available, i have to assign to itself on every set. Is that correct?

thanks

**Comment by arqex** [comment]
Hi @aptheod 

I would do something like 

```js
var data = this.data.set({ int_value: 5, array_2: [1,2,3] })
  .array_1.append( [4,5,6] )
;
```

But be aware of the `data` object returned, it will have the updated `array_1` node, instead of the `data` one, because the last operation is made on `this.data.array_1`.

If you don't have access to the `get()` method to restore the data object, your best option is use transactions

```js
var dataStore = new Freezer({
  data: { 
    array_1: [],
    int_value: 0,
    array_2: [],
    bool_value: false  
  }
});

var data = dataStore.get().data,
    trans = data.transact()
;

// trans is a mutable representation of data
// that holds all the changes in its children
trans.int_value = 5;
trans.array_2.reset([1,2,3]);
trans.array_2.append([4,5,6]);

// Run transaction
data = data.run();

console.log( data );
console.log( dataStore.get().data );
```
http://jsbin.com/noqikokiqa/2/edit

**Comment by arqex** [comment]
As a suggestion, always try to use freezer nodes from the store and never store local copies of them, like `this.data`. If the store gets updated your `this.data` won't, so your app will get out of sync.

**Comment by aptheod** [comment]
Thanks, for your detailed explanation. I used the transactions option and worked great!
