### ISSUE TITLE
"Example of use" sample output differs from expected output in comments

### ISSUE THREAD

**Issue by zenfe** [arqex/freezer#46]
The following code actually outputs "undefined" "false". The length of updatedB is actually 4.

```javascript
console.log( updatedB[4] ); // logs 100
console.log(updatedB.length === 5); // true: We added 2 elements and removed 1
```

Looks to me like the sample and comments are incorrect because only one new element was added and not 2.

**Comment by arqex** [comment]
Well spotted. I will update the readme file in the next version :)

Thanks @zenfe
