### ISSUE TITLE
Consider changing to MIT license

### ISSUE THREAD

**Issue by rrag** [arqex/freezer#5]
First off I should say this is an nice library, solves the purpose, easy to get started.
Listening to updates at each node is a nice feature and love it. Very nicely integrates with `shouldComponentUpdate`

I am using freezer in one of my projects but the GPL license is a deal breaker for me to move forward. Would you consider changing to MIT license?

**Comment by arqex** [comment]
Hi @rrag 
Thanks for your kind words.

I am no expert about licenses, if you are able to explain the difference between GPL and MIT ones to me, I'll be glad to change it.

Can a MIT licensed library be used in a GPL project?

**Comment by rrag** [comment]
MIT license is GPL-compatible, but the opposite is not true.

GPL does not make it open-source per se, but makes it free software.

The main issue here is, if there is a code modification made to a GPL licensed code and it is distributed, the source code also has to be distributed as open. But with MIT that is not needed.
In other words, it is impossible for software built on GPL to be distributed as closed source and not for free.

Some good points at [SO](http://stackoverflow.com/questions/3902754/mit-vs-gpl-license)

**Comment by arqex** [comment]
Thanks for the explanation,

I have changed the licensed to MIT, enjoy!

**Comment by rrag** [comment]
This is great, Thanks @arqex
