### ISSUE TITLE
"postMessage" error in react-native

### ISSUE THREAD

**Issue by yannisgu** [arqex/freezer#56]
Currently there is a bug in freezer when used in react-native. 
The error comes from here: https://github.com/arqex/freezer/blob/master/src/utils.js#L63

Error Message: `TypeError: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': The 2nd argument is neither an array, nor does it have indexed properties.`

**Comment by arqex** [comment]
Hi @yannisgu 

Thanks for spot the issue. I have just updated freezer trying to solve this but, unfortunatelly, using windows I can't use react-native yet and I can't check if the change is working.

Could you update your freezer install to v0.9.3 and try if this is fixed?

Thanks,
Javi

**Comment by yannisgu** [comment]
Hi Javi

0.9.3 fixed the problem, thank you very much!
