### ISSUE TITLE
bower.json is including the wrong file

### ISSUE THREAD

**Issue by pencilcheck** [arqex/freezer#57]
bower.json is including the wrong file for main.

The freezer.js in the root folder uses CommonJS which is not really used in a lot of projects using bower in the first place.

The right file that should be included in the main attribute should be the freezer.js file in the build folder instead.

**Comment by arqex** [comment]
Thanks @pencilcheck for the feedback, and sorry it took so long for me to fix it, but it should be working ok in v0.9.6
