### ISSUE TITLE
Replacing a node in freezer

### ISSUE THREAD

**Issue by rrag** [arqex/freezer#6]
I have a need to replace a node entirely, not merge with the existing node. I read through the issues and I see you have commented about it [here](https://github.com/arqex/freezer/issues/3#issuecomment-74873280), I modified the source to get this `replace` added to `mixin.js` where I publish a new event and listen to that on `frozen.js` with the same event name I published on `mixin.js`.

I got this to work. What I wanted to know is do you plan on implementing this feature yourself or is it already implemented and I just did not search enough? Will be happy to send a PR if it is not implemented already.

I don't want to go about doing `node.remove` for all the keys to be removed.

**Comment by marquex** [comment]
Hi @rrag 

Yes, that method would be really handy but also dangerous. The responsibility of replacing a part of the store should belong to the parent of the store, and a component that refreshes its store should be the exception.

Keep in mind that leaf nodes won't be able to replace themsevels anyway.

Said so, I think that the `replace` method would be useful. I am not sure about the mothod's name, `replace` has sense if it is the parent who replace some of its children, but a node can't replace itself, so maybe a name like `reset` would be more accurate.

If you send a PR with the `reset` I will review and merge it.

Thanks for your feedback

**Comment by rrag** [comment]
Cool, I will send a PR

The problem is in react when I send a few props to a component, it does not have access to the parent, and if I need to replace/reset that node I need this feature. I was using `set` and did not understand that it is actually merging and not just doing a overwrite.

so I understand this right,

```js
var store = new Freezer({
 	foo: { index: 0, bar: 'bar' }
});

var newFoo = store.get().foo.set({ index: 1, foobar: 'foobar' });
console.log(newFoo); // This prints { index: 1, foobar: 'foobar', bar:'bar' }

newFoo = store.get().foo.reset({ index: 2, lorem: 'ipsum' }); // I am adding this reset method to the mixin
console.log(newFoo); // This prints { index: 2, lorem: 'ipsum' }
```

Kindly confirm.

Also on a related note, I think [this](https://github.com/arqex/freezer/blob/master/src/frozen.js#L85) is better named `merge`, do you agree?

**Comment by arqex** [comment]
Yes you got it! Reset would delete the properties that are not passed as arguments.

And I agree that `merge` would be a better name for that method in frozen file. But be careful on update, you should also update https://github.com/arqex/freezer/blob/master/src/mixins.js#L36 to notify `merge`.

**Comment by rrag** [comment]
Thanks, will do

**Comment by arqex** [comment]
Added in https://github.com/arqex/freezer/commit/7ff624a4a12f4e2534e12d1af0c5873fdcc9ea51
