### ISSUE TITLE
React-pure-render integration

### ISSUE THREAD

**Issue by Tjorriemorrie** [arqex/freezer#61]
Does this library work with [react-pure-render](https://github.com/gaearon/react-pure-render)?

I've tried:

```
import shouldPureComponentUpdate from 'react-pure-render/function';
export default class App extends React.Component {
    shouldComponentUpdate = shouldPureComponentUpdate;
```

instead of:

```
freezer.on('update', () => this.forceUpdate());
```

But it didn't trigger an update.

**Comment by leesei** [comment]
I think the `forceUpdate()` call should be in the top most App component.
`react-pure-render` should be used for dumb components in the leaves of the component tree.

[Smart and Dumb Components — Medium](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0)

**Comment by Tjorriemorrie** [comment]
OK, so I assume it's useless then because of how freezer works. Thanks for the advice.

**Comment by arqex** [comment]
@Tjorriemorrie there is no problem using freezer and react-pure-render together. Your freezer store should be read by your top component (as @leesei recommends ) and its data is passed down through its children props. Only this top component should use the `forceUpdate` snippet to make your app reactive.

All the children should receive the data from their props and they can be pure components, getting the benefit of using react-pure-render.

**Comment by leesei** [comment]
I've updated my comment.

@arqex do you think my commit is useful for freezer-todomvc?
I can create PR after changing dependency to `react-pure-render`.
