### ISSUE TITLE
markDirty is not defined

### ISSUE THREAD

**Issue by dangreen** [arqex/freezer#65]
https://github.com/arqex/freezer/blob/master/src/frozen.js#L189

**Comment by dangreen** [comment]
@arqex helloooo??

**Comment by bep** [comment]
@arqex same problem here.

**Comment by arqex** [comment]
Thanks for the feedback, and sorry for the late reply, christmas time was a tough time for working :)

I knew about this problem I had it fixed in my local version. Now I pushed it and should be fixed in v0.9.5.

Cheers

**Comment by arqex** [comment]
v0.9.5 was published buggy, try v0.9.6 instead
