### ISSUE TITLE
Parents reference of some children not updated after reset

### ISSUE THREAD

**Issue by hunteva** [arqex/freezer#94]
## Symptom

![image](https://cloud.githubusercontent.com/assets/491380/18934664/86149638-8637-11e6-8f79-fe2a49bb3d2d.png)

## Cause

fixChildren leave the parents of deeper child unchanged in some cases.

## Fix

PR: [https://github.com/arqex/freezer/pull/93](https://github.com/arqex/freezer/pull/93)

**Comment by arqex** [comment]
Merged #93
